/**
 SHA1
 by Craig Spitzkoff <craig@spitzkoff.com>
 http://spitzkoff.com/craig/?p=122
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OF OTHER DEALINGS IN THE SOFTWARE.
 */
#import <Foundation/Foundation.h>

@interface SHA1 : NSObject

+(NSString*)digest:(NSString*)input;

@end